# Generated by Django 4.2.3 on 2023-08-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('link', models.TextField()),
                ('belt', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
